### PR TITLE
Handle error in MM and RG api

### LINKED ISSUE #32: handle error in MM and RG API
# Problem Statement
Handle error in MM and RG API with a signature that allow to undestand that the API of MM or RG can failed, for e.g `Either[MMError, MatchedRoute` or Try[MatchedRoute]

### PR DESCRIPTION
**Pull request by pierDipi**
# New features and improvements

- Use `Either[MatchedRouteError, MatchedRoute]` as return value of `RouteMatcher.match` 
- Use `Either[ReverseGeocodingError, ReverseGeocodingResponse]` as return value of `ReverseGeocoder.reverseGeocode` 

# Related issue

Closes #32

### CODE REVIEW

File: src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala [hunk 1]
```diff
@@ -19,12 +20,10 @@ case class GraphHopperManager(conf: Config) extends RouteMatcher with Logger {
       //TODO is this right?
       .getOrElse("unclassified")
 
-
   @throws(classOf[RuntimeException])
   @throws(classOf[IllegalAccessException])
-  override def matchingRoute(gpsPoints: Seq[GPSPoint]): MatchedRoute = {
-
-    val calcRoute: MatchResult = graphConf.mapMatching.doWork(gpsPoints.map(_.toGPXEntry))
+  private def getMatchingRoute(gpsPoints: Seq[GPSPoint]) = {
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala:25]: I would handle the error in this method and propagate it to the caller

File: src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/MatchedRoute.scala [hunk 2]
```diff
@@ -70,3 +70,10 @@ case class MatchedRoute(points: Seq[TracePoint],
   }
 
 }
+
+/**
+ * Matcher route error.
+ *
+ * @param ex error reason.
+ */
+case class MatchedRouteError(ex: Throwable)
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/MatchedRoute.scala:79]: I would create a package object exceptions and insert the two exceptions for mm and rg here

File: src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala [hunk 3]
```diff
@@ -17,9 +17,9 @@ case class OSMManager(conf: Config) extends ReverseGeocoder with Logger {
   val osmConfig: OSMManagerConfiguration = OSMManagerConfiguration(conf)
   val indexManager: IndexManager = IndexManager(osmConfig.indexConf)
 
-  override def reverseGeocode(point: GPSPoint): ReverseGeocodingResponse = {
+  override def reverseGeocode(point: GPSPoint): Either[ReverseGeocodingError, ReverseGeocodingResponse] = {
     val queryPoint: Point = new GeometryFactory().createPoint(new Coordinate(point.lon, point.lat))
-    makeAddress(reverseGeocodeQueryingBoundaries(queryPoint), reverseGeocodeQueryingStreets(queryPoint), queryPoint)
+    Right(makeAddress(reverseGeocodeQueryingBoundaries(queryPoint), reverseGeocodeQueryingStreets(queryPoint), queryPoint))
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala:22]: what happen if reverseGeocodeQueryingStreets return an Exception? You are create a Right for an exception. 
I would try to figure out if this API can go wrong in exception.

File: src/main/scala/it/agilelab/bigdata/gis/domain/models/ReverseGeocodingResponse.scala [hunk 4]
```diff
@@ -51,4 +51,6 @@ case class ReverseGeocodingResponse(street: Option[String],
                                     speedLimit: Option[Int] = None,
                                     speedCategory: Option[String] = None,
                                     roadType: Option[String] = None,
-                                    distance: Option[Double] = None) extends OutputModel
\ No newline at end of file
+                                    distance: Option[Double] = None) extends OutputModel
+
+case class ReverseGeocodingError()
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/models/ReverseGeocodingResponse.scala:56]: I would create a package object exceptions and insert the two exceptions for mm and rg here

File: src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala [hunk 5]
```diff
@@ -4,17 +4,17 @@ import com.typesafe.config.{Config, ConfigFactory}
 import it.agilelab.bigdata.gis.domain.graphhopper.GPSPoint
 import it.agilelab.bigdata.gis.domain.managers.OSMManager
 import it.agilelab.bigdata.gis.domain.models.ReverseGeocodingResponse
-import org.scalatest.{BeforeAndAfterAll, FlatSpec, Matchers}
+import org.scalatest.{BeforeAndAfterAll, EitherValues, FlatSpec, Matchers}
```
Comment (andr3a87) [inline src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala:7]: is it necessary EitherValues?

Comment (pierDipi) [reply src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala:7]: Not really, we can directly use `obj.right.get`, but [`EitherValues` `scalatest` doc says](https://www.scalatest.org/user_guide/using_EitherValues):
> The NoSuchElementException would cause the test to fail, but without providing a stack depth pointing to the failing line of test code. This stack depth, provided by TestFailedException (and a few other ScalaTest exceptions), makes it quicker for users to navigate to the cause of the failure. Without EitherValues, to get a stack depth exception you would need to make two statements
> ```
> either should be ('right) // throws TestFailedException
> either.right.get should be > 9
> ```

So, my preference would be to stay with `EitherValues` for the above reason.

Comment (pierDipi) [reply src/test/scala/it/agilelab/bigdata/gis/domain/loader/OSMManagerSpec.scala:7]: wdyt?

File: src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala (hunk 3 above)
Comment (pierDipi) [reply src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala]: Done!

File: src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala (hunk 1 above)
Comment (giorgio84) [reply src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala:25]: I agree with Andrea, also because otherwise, the caller doesn't have any visibility that this method could fail for any reason.

Comment (pierDipi) [reply src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala]: Done, PTAL.

File: src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala [hunk 6]
```diff
@@ -19,138 +20,138 @@ case class GraphHopperManager(conf: Config) extends RouteMatcher with Logger {
       //TODO is this right?
       .getOrElse("unclassified")
 
+  override def matchingRoute(gpsPoints: Seq[GPSPoint]): Either[MatchedRouteError, MatchedRoute] = {
+    try {
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala:24]: use a Try

File: src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala [hunk 7]
```diff
@@ -19,138 +20,138 @@ case class GraphHopperManager(conf: Config) extends RouteMatcher with Logger {
...
+        Right(MatchedRoute(
+          points,
+          length,
+          time,
+          routeTypesKm,
+          distancesBetweenNode
+        ))
+      } else
+          Right(MatchedRoute(gpsPoints.map(_.toTracePoint), length, time, Map.empty, Seq.empty))
+    } catch {
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/graphhopper/GraphHopperManager.scala:153]: use pattern matching with 
Success => Right(...)
Failure => Left(..)

File: src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala [hunk 8]
```diff
@@ -4,22 +4,27 @@ import com.typesafe.config.Config
...
   val osmConfig: OSMManagerConfiguration = OSMManagerConfiguration(conf)
   val indexManager: IndexManager = IndexManager(osmConfig.indexConf)
 
-  override def reverseGeocode(point: GPSPoint): ReverseGeocodingResponse = {
+  override def reverseGeocode(point: GPSPoint): Either[ReverseGeocodingError, ReverseGeocodingResponse] = {
     val queryPoint: Point = new GeometryFactory().createPoint(new Coordinate(point.lon, point.lat))
-    makeAddress(reverseGeocodeQueryingBoundaries(queryPoint), reverseGeocodeQueryingStreets(queryPoint), queryPoint)
+    Try(makeAddress(reverseGeocodeQueryingBoundaries(queryPoint), reverseGeocodeQueryingStreets(queryPoint), queryPoint)) match {
+      case Success(addr) => Right(addr)
+      case Failure(ex) => Left(ReverseGeocodingError(ex))
```
Comment (andr3a87) [inline src/main/scala/it/agilelab/bigdata/gis/domain/managers/OSMManager.scala:26]: add a logger.error

**Review by andr3a87 — APPROVED** [review]
